# apiVersion: v1
# kind: Service
# metadata:
#   name: myapp-service
# spec:
#   selector:
#     app: myapp
#   ports:
#   - port: 8080
#     protocol: TCP
#     targetPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
